apiVersion: v1
kind: LimitRange
metadata:
  name: votingapp
  namespace: votingapp
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 50Mi
      default: # default limit
        cpu: 100m
        memory: 200Mi
      min:
        cpu: 5m     # container need at least 5m of cpu to be scheduled
        memory: 10Mi
      max:
        cpu: 200m   # container can request no more than 200m of cpu
        memory: 300Mi
      
