#apiVersion: gateway.networking.k8s.io/v1beta1
#kind: ReferenceGrant
#metadata:
#  name: allow-votingapp-routes
#  namespace: gw-votingapp
#spec:
#  from:
#  - group: gateway.networking.k8s.io
#    kind: HTTPRoute
#    namespace: votingapp-dev
#  to:
#  - group: ""
#    kind: Service
