apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-managed-disk
  namespace: votingapp
spec:
# Default SC of AKS. It leverages the CSI driver. https://learn.microsoft.com/en-us/azure/aks/azure-csi-disk-storage-provision#built-in-storage-classes
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
